/**
 * This file is autogenerated. Do not edit by hand — run `pnpm generate`.
 *
 * Non-local chain deployments live here; local (chainId 31337)
 * deployments live in `./MYSTToken.local.ts` (gitignored) and are merged in
 * at module load. Import by name: `import { MYSTToken } from "~~/contracts/MYSTToken";`
 */
import { MYSTToken as MYSTToken_LOCAL } from "./MYSTToken.local";
import type { ContractDeployment } from "~~/utils/contract";

const REMOTE = {
  11155111: {
    address: "0xE83A10Fb404Fecc97bAf2AA35Cd13Bc35eCf6F2e",
    abi: [
      {
        type: "constructor",
        inputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "FAUCET_AMOUNT",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint64",
            internalType: "uint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "FAUCET_COOLDOWN",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "balanceOf",
        inputs: [
          {
            name: "account",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "canClaimFaucet",
        inputs: [
          {
            name: "user",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bool",
            internalType: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "claimFaucet",
        inputs: [],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "confidentialProtocolId",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "decimals",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint8",
            internalType: "uint8",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "name",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "string",
            internalType: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "owner",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "setTipMyst",
        inputs: [
          {
            name: "_tipMyst",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "symbol",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "string",
            internalType: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "tipMyst",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "tipTransfer",
        inputs: [
          {
            name: "from",
            type: "address",
            internalType: "address",
          },
          {
            name: "to",
            type: "address",
            internalType: "address",
          },
          {
            name: "amount",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "FaucetClaimed",
        inputs: [
          {
            name: "user",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "Transfer",
        inputs: [
          {
            name: "from",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "to",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
      {
        type: "error",
        name: "FaucetCooldown",
        inputs: [],
      },
      {
        type: "error",
        name: "NotOwner",
        inputs: [],
      },
      {
        type: "error",
        name: "OnlyTipMyst",
        inputs: [],
      },
      {
        type: "error",
        name: "TipMystAlreadySet",
        inputs: [],
      },
      {
        type: "error",
        name: "ZamaProtocolUnsupported",
        inputs: [],
      },
    ],
    deployedOnBlock: 10791010,
  },
} as const;

export const MYSTToken = {
  ...REMOTE,
  ...MYSTToken_LOCAL,
} as const satisfies Partial<Record<number, ContractDeployment>>;
