/**
 * This file is autogenerated. Do not edit by hand — run `pnpm generate`.
 *
 * Non-local chain deployments live here; local (chainId 31337)
 * deployments live in `./TipMyst.local.ts` (gitignored) and are merged in
 * at module load. Import by name: `import { TipMyst } from "~~/contracts/TipMyst";`
 */
import { TipMyst as TipMyst_LOCAL } from "./TipMyst.local";
import type { ContractDeployment } from "~~/utils/contract";

const REMOTE = {
  11155111: {
    address: "0x9C6174C7E452C5ECe8A87E639Da10eb9db0a6439",
    abi: [
      {
        type: "constructor",
        inputs: [
          {
            name: "_token",
            type: "address",
            internalType: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "confidentialProtocolId",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getAllCreators",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "address[]",
            internalType: "address[]",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getCreator",
        inputs: [
          {
            name: "addr",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "_name",
            type: "string",
            internalType: "string",
          },
          {
            name: "_bio",
            type: "string",
            internalType: "string",
          },
          {
            name: "_imageUrl",
            type: "string",
            internalType: "string",
          },
          {
            name: "_tipCount",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getCreatorCount",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "isCreator",
        inputs: [
          {
            name: "addr",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bool",
            internalType: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "registerCreator",
        inputs: [
          {
            name: "_name",
            type: "string",
            internalType: "string",
          },
          {
            name: "_bio",
            type: "string",
            internalType: "string",
          },
          {
            name: "_imageUrl",
            type: "string",
            internalType: "string",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "sendTip",
        inputs: [
          {
            name: "creator",
            type: "address",
            internalType: "address",
          },
          {
            name: "encAmount",
            type: "bytes32",
            internalType: "externalEuint64",
          },
          {
            name: "inputProof",
            type: "bytes",
            internalType: "bytes",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "token",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "address",
            internalType: "contract MYSTToken",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "event",
        name: "CreatorRegistered",
        inputs: [
          {
            name: "creator",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "name",
            type: "string",
            indexed: false,
            internalType: "string",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "TipSent",
        inputs: [
          {
            name: "from",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "to",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
      {
        type: "error",
        name: "AlreadyRegistered",
        inputs: [],
      },
      {
        type: "error",
        name: "EmptyName",
        inputs: [],
      },
      {
        type: "error",
        name: "NotRegistered",
        inputs: [],
      },
      {
        type: "error",
        name: "SelfTip",
        inputs: [],
      },
      {
        type: "error",
        name: "SenderNotAllowedToUseHandle",
        inputs: [
          {
            name: "handle",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "sender",
            type: "address",
            internalType: "address",
          },
        ],
      },
      {
        type: "error",
        name: "ZamaProtocolUnsupported",
        inputs: [],
      },
    ],
    deployedOnBlock: 10791010,
  },
} as const;

export const TipMyst = {
  ...REMOTE,
  ...TipMyst_LOCAL,
} as const satisfies Partial<Record<number, ContractDeployment>>;
